# Generated by Django 4.2.7 on 2025-10-31 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('recurring', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'verbose_name': 'Leave Balance', 'verbose_name_plural': 'Leave Balances'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='carried_forward_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='total_earned_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='address_during_leave',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='requires_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Cancelled')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='LeaveAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accrual_date', models.DateField()),
                ('days_accrued', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_accruals', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaves.leavetype')),
            ],
        ),
    ]
