# Generated by Django 4.2.7 on 2025-10-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_holiday_alter_leavebalance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaveaccrual',
            options={'ordering': ['-accrual_date'], 'verbose_name': 'Leave Accrual', 'verbose_name_plural': 'Leave Accruals'},
        ),
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
